# Generated by Django 5.2.4 on 2026-07-28 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_status', models.CharField(choices=[('pending', 'Pending Approval'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20, verbose_name='Order Status')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Order Description')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Order Date')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-order_date'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Service Name')),
                ('service_type', models.CharField(choices=[('سئو', 'Seo'), ('طراحی وبسایت', 'Website Design'), ('توسعه نرم افزار', 'Software Dev'), ('سایر', 'Other')], default='سایر', max_length=20, verbose_name='Service Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('duration_days', models.PositiveIntegerField(default=1, help_text='Time required to complete the service in days', verbose_name='Duration (Days)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
                'ordering': ['name'],
            },
        ),
    ]
