# Generated by Django 5.2.4 on 2026-07-29 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
